In [2]:
import seaborn as sns

from reasoning_fine_tune.analysis.standard_analysis import standard_analysis_single_token_response

sns.set_theme(palette="deep")

standard_analysis_single_token_response(
    "../../../data/out/single_token_entropy/mmlu_qwen_3b.tsv",
    "entropy_ans_qwen2",
    "entropy_ans_correct_qwen2",
    "entropy_value_qwen2",
    "",
    show=["tables"],
)
standard_analysis_single_token_response(
    "../../../data/out/single_token_entropy/mmlu_qwen_3b_mid_pipeline.tsv",
    "entropy_ans_qwen2",
    "entropy_ans_correct_qwen2",
    "entropy_value_qwen2",
    "",
    show=["tables"],
)
# Not applicable due to distillation training
# standard_analysis_single_token_response(
#     "../../../data/out/single_token_entropy/mmlu_qwen_3b_after_pipeline.tsv",
#     "entropy_ans_qwen2",
#     "entropy_ans_correct_qwen2",
#     "entropy_value_qwen2",
#     "",
#     show=["tables"],
# )

entropy_ans_qwen2
9      2371
1      1928
2      1728
3      1691
5      1331
4      1276
7       672
8       599
6       428
NaN       8
Name: count, dtype: int64
entropy_ans_qwen2
9    2371
1    1928
2    1728
3    1691
5    1331
4    1276
7     672
8     599
6     428
Name: count, dtype: int64

,category,roc_auc,accuracy,gini,num_samples,model,metric
0,ALL,0.719326,0.339547,0.438653,10782,,entropy_value_qwen2
1,law,0.626185,0.237624,0.252370,1010,,entropy_value_qwen2
2,business,0.676167,0.279614,0.352334,726,,entropy_value_qwen2
3,psychology,0.770901,0.511905,0.541802,756,,entropy_value_qwen2
4,chemistry,0.689268,0.236052,0.378537,932,,entropy_value_qwen2
5,biology,0.788458,0.590975,0.576916,687,,entropy_value_qwen2
6,history,0.667878,0.351801,0.335756,361,,entropy_value_qwen2
7,other,0.705028,0.330673,0.410057,877,,entropy_value_qwen2
8,physics,0.661758,0.286348,0.323516,1128,,entropy_value_qwen2
9,computer science,0.748809,0.284211,0.497617,380,,entropy_value_qwen2
10,health,0.692167,0.387931,0.384333,696,,entropy_value_qwen2
11,economics,0.760697,0.445420,0.521394,797,,entropy_value_qwen2
12,math,0.698614,0.247162,0.397227,1145,,entropy_value_qwen2
13,philosophy,0.659621,0.325773,0.319243,485,,entropy_value_qwen2
14,engineering,0.657763,0.362843,0.315526,802,,entropy_value_qwen2
15,graduate,0.652216,0.282528,0.304432,2152,,entropy_value_qwen2
16,undergraduate,0.731553,0.356832,0.463107,6213,,entropy_value_qwen2
17,high_school_and_easier,0.734988,0.353474,0.469976,2317,,entropy_value_qwen2
18,postgraduate,0.653437,0.170000,0.306875,100,,entropy_value_qwen2
19,medium,0.717312,0.319622,0.434623,7099,,entropy_value_qwen2
20,low,0.720007,0.422816,0.440013,2656,,entropy_value_qwen2
21,high,0.641161,0.261928,0.282322,1027,,entropy_value_qwen2

,category,roc_auc,accuracy,gini,num_samples,model,metric
0,ALL,0.528418,0.339547,0.056835,10782,,masj_edu_level_norm

,category,roc_auc,accuracy,gini,num_samples,model,metric
0,ALL,0.553801,0.339547,0.107603,10782,,masj_num_reasoning_steps_norm

entropy_ans_qwen2
1    3198
4    2267
3    1364
2    1267
9    1130
5     970
7     674
8     619
6     543
Name: count, dtype: int64
entropy_ans_qwen2
1    3198
4    2267
3    1364
2    1267
9    1130
5     970
7     674
8     619
6     543
Name: count, dtype: int64

,category,roc_auc,accuracy,gini,num_samples,model,metric
0,ALL,0.728555,0.366728,0.457111,10790,,entropy_value_qwen2
1,law,0.635681,0.269307,0.271361,1010,,entropy_value_qwen2
2,business,0.682698,0.272727,0.365396,726,,entropy_value_qwen2
3,psychology,0.765777,0.544974,0.531553,756,,entropy_value_qwen2
4,chemistry,0.686825,0.269025,0.373649,933,,entropy_value_qwen2
5,biology,0.816921,0.622093,0.633843,688,,entropy_value_qwen2
6,history,0.618940,0.387812,0.237880,361,,entropy_value_qwen2
7,other,0.685110,0.367161,0.370220,877,,entropy_value_qwen2
8,physics,0.671170,0.292553,0.342341,1128,,entropy_value_qwen2
9,computer science,0.749411,0.336842,0.498822,380,,entropy_value_qwen2
10,health,0.726316,0.413793,0.452631,696,,entropy_value_qwen2
11,economics,0.788069,0.472431,0.576139,798,,entropy_value_qwen2
12,math,0.668218,0.293043,0.336436,1150,,entropy_value_qwen2
13,philosophy,0.674718,0.371134,0.349435,485,,entropy_value_qwen2
14,engineering,0.679161,0.366584,0.358321,802,,entropy_value_qwen2
15,graduate,0.690647,0.310441,0.381295,2155,,entropy_value_qwen2
16,undergraduate,0.736552,0.384046,0.473104,6218,,entropy_value_qwen2
17,high_school_and_easier,0.733399,0.378075,0.466798,2317,,entropy_value_qwen2
18,postgraduate,0.610746,0.240000,0.221491,100,,entropy_value_qwen2
19,medium,0.724029,0.347832,0.448058,7104,,entropy_value_qwen2
20,low,0.729286,0.452014,0.458573,2657,,entropy_value_qwen2
21,high,0.677325,0.276968,0.354650,1029,,entropy_value_qwen2

,category,roc_auc,accuracy,gini,num_samples,model,metric
0,ALL,0.525422,0.366728,0.050844,10790,,masj_edu_level_norm

,category,roc_auc,accuracy,gini,num_samples,model,metric
0,ALL,0.554794,0.366728,0.109588,10790,,masj_num_reasoning_steps_norm